# Generated by Django 3.0.6 on 2020-05-10 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_photo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='last_accurance',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
